services:
  - type: web
    name: birthday-web
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node mail.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
    autoDeploy: true
